#!/bin/sh
### BEGIN INIT INFO
# Provides:          actuator-bigsea.service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       BigSea Actuator Service
### END INIT INFO

dir="/opt/actuator-bigsea"
cmd="python $dir/actuator-server.py"
user="root"

name="actuator-bigsea.service"
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"

start() {
  if [ -f $pid_file ] && kill -0 $(cat $pid_file); then
    echo 'Service already running'
    return 1
  fi
  echo 'Starting service…'
  $cmd >> "$stdout_log" &
  echo $! > $pid_file
  echo 'Service started'
}

stop() {
  if [ ! -f "$pid_file" ] || ! kill -0 $(cat "$pid_file"); then
    echo 'Service not running'
    return 1
  fi
  echo 'Stopping service…'
  kill -9 $(cat "$pid_file")
  rm -f "$pid_file"
  echo 'Service stopped'
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$pid_file"
    echo "Notice: log file is not be removed: '$stdout_log'" >&2
    update-rc.d -f $name remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
